### ISSUE TITLE
UE 5.1 Config asset crash

### ISSUE THREAD

**Issue by nli2work** [Animation-Uprising/MotionSymphony_ExampleProject#8] opened 2022-12-08 15:24 UTC
crash when adding Pose Bone in new MotionMatching Config asset. Existing Config asset with Pose Bone assignments from UE 5.0 will crash on open in UE 5.1. Exisiting MM setups still work without any apparent issue. Can't modify or create Config Assets.

```
LogWindows: Error: appError called: LowLevelFatalError [File:E:\FirstAscent_UGS\Engine\Source\Runtime\Engine\Classes\Interfaces\Interface_BoneReferenceSkeletonProvider.h] [Line: 35] 
Pure virtual not implemented (IBoneReferenceSkeletonProvider::GetSkeleton)
```

**Comment by Avindr** [comment] 2022-12-20 01:32
This was caused by some changes in the IBoneReferenceSkeletonProvider in UE5.1 API.

It has been fixed with the latest deployment which contains several updates for compatibility with UE5.1.

**Closed as completed by Avindr** 2022-12-20 01:32 UTC
Labels: bug
